### ISSUE TITLE
(Wiki issue) The Wiki pages for the scripting is NOT that helpful.

### ISSUE THREAD

**Issue by MCAlexisYT** [Blancworks/Figura#148]
I'm searching for a Lua scripting tutorial made specifically for this mod only to find a bedrock-walled dead end. Then I turned to the Figura Wiki only to be confused by the vague non-sense within. But at least it contains helpful information.

**Comment by DraconicLuca** [comment]
true, the wiki needs a rewrite

**Comment by 0xf24** [comment]
For right now, if you need help I recommend joining the figura discord, https://discord.gg/figura

**Comment by Fishvap** [comment]
The Figura Wiki will be rewritten from the introduction of 0.0.7.

**Comment by MCAlexisYT** [comment]
The wiki DIDN'T GET REWRITTEN. AND ALPHA 7 IS OUT. I knew that I was lied to at least once.

**Comment by MCAlexisYT** [comment]
@0xf24 Hey, the wiki isn't rewritten even though Alpha 7 is out. Why?

**Comment by GrandpaScout** [comment]
There is a new wiki project currently being worked on. Be patient.

**Comment by Manuel-3** [comment]
> I knew that I was lied to at least once.

At the time this was posted, the wiki was planned to be updated, however plans have changed. The mod is being rewritten from the ground up and at first the rewritten version was planned to be released as 0.0.7, but the development got delayed so instead the rewrite will be 0.1.0 (at least as far as I know).

Instead of a wiki, features for 0.0.7 as well as 0.0.8 pre releases can be viewed in the changelogs in the pre-releases channel on the discord server. Also check out pinned messages in the help channel.

**Comment by 0xf24** [comment]
A. Not even sure who was the person who promised that the wiki was going to be rewritten for 7, but it wasn't a developer.
B. This is a free mod, written by volunteers in their spare time. We do not get paid. We do this because we enjoy it. Do not be the reason we stop enjoying it.
C. As stated before there is a discord you can join where there are plenty of people willing to help you, provided that you are patient, civil, and don't yell at them.

@MCAlexisYT

**Comment by MCAlexisYT** [comment]
@0xf24 
_[ERROR: CANNOT JOIN DISCORD SERVER]_

**Comment by MCAlexisYT** [comment]
@Manuel-3 Yeah, it's like how the Caves and Cliffs update was split in half and the warden was subsequently delayed until the Wild Update

**Comment by GrandpaScout** [comment]
This issue has been marked as `invalid`.
Not much is going to be done about this specific issue anymore.

**Comment by 0xf24** [comment]
Lol you got banned from discord for being toxic. @ me again and I'll figure out how to use the GitHub moderation tools

**Comment by TheOneTrueZandra** [comment]
I'm closing this to prevent any further conflict and drama.

The wiki will bet getting a polish in the future, but I don't feel like this issue is particularly conducive to that actually happening.
