### ISSUE TITLE
(Question) Vanilla model visibility

### ISSUE THREAD

**Issue by ewewukek** [Blancworks/Figura#164]
is there a reason why vanilla model is visible by default?
I'm trying to make basic modifications to default player model but forced to add a script just to hide vanilla model

**Comment by TheOneTrueZandra** [comment]
There's no way to tell if an avatar is built to entirely replace the vanilla model, add to it, or just manipulate it.

We opted for the simplest case, where someone wants to keep their vanilla skin, but add things to it (like hats or something), rather than forcing people to re-create their model every time from scratch.

**Comment by ewewukek** [comment]
wiki didn't make that clear)
Blockbench's "Minecraft Skin" preset creates complete player model so I got confused when mod showed layers that I removed from the model causing z-fighting
